### ISSUE TITLE
Erro ao instalar br_coa "Plano de Contas Simplificado Brasil"

### ISSUE THREAD

**Issue by deyvsonaguiar** [Trust-Code/trustcode-addons#28]
Olá meus caros, 

Instalei o sistema em um server online e gostaria de tirar essa dúvida. Mais uma dica de como posso instalar o br_coa sem o mesmo ficar "A ser instalado" no sistema. Podem me dizer se já tiveram que lidar com esse probleminha e como resolveram? Grato. 

Segue log do Odoo 10:

Traceback (most recent call last):
  File "/root/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/root/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/root/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/root/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/root/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/root/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/root/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/root/odoo/addons/web/controllers/main.py", line 882, in call_button
    action = self._call_kw(model, method, args, {})
  File "/root/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/root/odoo/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/root/odoo/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/root/odoo/odoo/addons/base/module/module.py", line 410, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/root/odoo/odoo/addons/base/module/module.py", line 484, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/root/odoo/odoo/modules/registry.py", line 78, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/root/odoo/odoo/modules/loading.py", line 339, in load_modules
    loaded_modules, update_module)
  File "/root/odoo/odoo/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/root/odoo/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/root/odoo/odoo/modules/loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/root/odoo/odoo/tools/convert.py", line 848, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/root/odoo/odoo/tools/convert.py", line 918, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/root/odoo/odoo/tools/convert.py", line 802, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/root/odoo/odoo/tools/convert.py", line 710, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/root/odoo/odoo/addons/base/ir/ir_model.py", line 1192, in _update
    record = record.create(values)
  File "/root/odoo/odoo/models.py", line 3811, in create
    record = self.browse(self._create(old_vals))
  File "/root/odoo/odoo/models.py", line 3901, in _create
    cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
  File "/root/odoo/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/root/odoo/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
ParseError: "duplicate key value violates unique constraint "account_tax_template_name_company_uniq"
DETAIL:  Key (name, company_id, type_tax_use)=(IPI Sa\xedda 3%, 1, sale) already exists.
" while parsing /root/odoo/odoo-brasil/br_coa/data/account_tax_template_data.xml:28, near
<record id="tax_template_out_ipi" model="account.tax.template">
        <field name="description">IPI Sa&#237;da 3%</field>
        <field name="name">IPI Sa&#237;da 3%</field>
        <field name="domain">ipi</field>
        <field name="amount">3.00</field>
        <field name="type_tax_use">sale</field>
        <field ref="id_2_1_4_03_010" name="account_id"/>
        <field ref="id_2_1_4_03_010" name="refund_account_id"/>
        <field ref="id_3_2_2_03_006" name="deduced_account_id"/>
        <field ref="id_3_2_2_03_006" name="refund_deduced_account_id"/>
        <field eval="0" name="price_include"/>
        <field ref="br_account_chart_template" name="chart_template_id"/>
    </record>

**Comment by danimaribeiro** [comment]
Você já instalou um plano de contas.
Remova o anterior.

**Comment by deyvsonaguiar** [comment]
Bem, tenho instalado o Brazilian Localization Account o "br_account". Para eu ficar com o br_coa teria que desinstalar esse? O que perderia?

**Comment by danimaribeiro** [comment]
O módulo se chama l10n_br
ele é um plano de contas igual ao br_coa
http://www.portaldecontabilidade.com.br/guia/planodecontas.htm

**Comment by deyvsonaguiar** [comment]
Obrigado Danimar, ótima aula!
