### ISSUE TITLE
Erro ao gerar fluxo de caixa

### ISSUE THREAD

**Issue by deyvsonaguiar** [Trust-Code/trustcode-addons#74]
Estou com um erro no módulo "Cash Flow Report", feito git diretamente do repositório da Trustcode com branch 10.0. O mesmo dá esse erro ao pôr uma data final (dia atual como última data), e ao clicar em imprimir da o seguinte erro, e na tela do sistema, quando climamos em gerar também mostra a seguinte mensagem:

"Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application". 

Já desinstalei, instalei novamente, dei novo git, e também instalei e atualizei o módulo mas persiste, alguma dica de solução?

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/odoo/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/opt/odoo/odoo/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/opt/odoo/odoo/addons/report/models/report.py", line 178, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/opt/odoo/odoo/addons/report/models/report.py", line 144, in get_html
    return self.render(report.report_name, docargs)
  File "/opt/odoo/odoo/addons/report/models/report.py", line 120, in render
    return view_obj.render_template(template, values)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1039, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/opt/odoo/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1059, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: No module named plotly.graph_objs
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_account_cash_flow_account_cash_flow_template_html_report_1000
  File "<template>", line 3, in body_call_content_999
  File "<template>", line 4, in body_call_content_998
  File "/opt/odoo/odoo/trustcode-addons/account_cash_flow/models/cash_flow_report.py", line 65, in draw_chart
    import plotly.graph_objs as go
ImportError: No module named plotly.graph_objs

Error to render compiling AST
ImportError: No module named plotly.graph_objs
Template: account_cash_flow.account_cash_flow_template_html_report
Path: /templates/t/t/t/div[1]/t
Node: <t t-raw="docs[0].draw_chart()"/>

**Comment by mstuttgart** [comment]
No meu caso tive que instalar o ploty e verificar a versão das dependências que estava usando. Se me lembro, uma das dependências do plotly dava conflito com a versão que outra lib usada da mesma dependência. Só não lembro agora qual dependência era (era algo relacionado a XML).

**Comment by deyvsonaguiar** [comment]
Na verdade, eu fiz o seguinte e me resolveu: 
$ pip install plotly

Daí reiniciei o odoo e deu a falta do Pandas como dependência. 

$sudo apt-get install python-pandas

$sudo service odoo restart

Funcionando perfeitamente!

Obrigado a dica @mstuttgart !
